name: build

on:
  push:
    branches:
      - develop
      - master
      - feature/chronicle-v3
  pull_request:
    branches:
      - develop
      - master
      - feature/chronicle-v3

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [latest]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: ${{ matrix.node-version }}

      - name: npm config
        env:
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
        run: |
          npm config set "@fortawesome:registry" https://npm.fontawesome.com/
          npm config set "//npm.fontawesome.com/:_authToken" "$FONTAWESOME_NPM_AUTH_TOKEN"

      # https://docs.npmjs.com/cli/v6/commands/npm-ci
      - name: npm ci
        run: npm ci

      - name: npm run lint
        run: npm run lint

      - name: npm run flow
        run: npm run flow

      - name: npm run test
        run: npm run test

      - name: npm run build:prod
        run: npm run build:prod

      - name: codecov
        uses: codecov/codecov-action@v1
